name: Bug Report
description: Reporta un error para ayudarnos a mejorar.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor, llena la siguiente información.
  - type: textarea
    id: description
    attributes:
      label: Descripción del Bug
      placeholder: Describe qué está pasando...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1. Iniciar la app
        2. Ir a '/'
        3. Ver el error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: ¿Qué debería pasar?
      placeholder: Describe el comportamiento esperado.
